import type { MasterTest } from "./types";

export const MASTER_TESTS: MasterTest[] = [
  {
    id: "mst-cbc",
    code: "CBC",
    name: "Complete Blood Count",
    department: "Hematology",
    sampleType: "EDTA whole blood",
    turnaroundHours: 4,
    listPrice: 350,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No special preparation. Stay hydrated.",
  },
  {
    id: "mst-fbs",
    code: "FBS",
    name: "Fasting Blood Sugar (Glucose)",
    department: "Biochemistry",
    sampleType: "Fluoride plasma",
    turnaroundHours: 4,
    listPrice: 120,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Fast for 8–12 hours. Water is allowed. Avoid alcohol for 24 hours.",
  },
  {
    id: "mst-ppbs",
    code: "PPBS",
    name: "Post-Prandial Blood Sugar",
    department: "Biochemistry",
    sampleType: "Fluoride plasma",
    turnaroundHours: 4,
    listPrice: 120,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Eat a regular meal, then draw sample exactly 2 hours later.",
  },
  {
    id: "mst-hba1c",
    code: "HBA1C",
    name: "HbA1c (Glycated Hemoglobin)",
    department: "Biochemistry",
    sampleType: "EDTA whole blood",
    turnaroundHours: 6,
    listPrice: 550,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No fasting required.",
  },
  {
    id: "mst-vitd",
    code: "VITD",
    name: "Vitamin D (25-OH)",
    department: "Endocrinology",
    sampleType: "Serum",
    turnaroundHours: 24,
    listPrice: 1200,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No special preparation. List current supplements.",
  },
  {
    id: "mst-b12",
    code: "B12",
    name: "Vitamin B12",
    department: "Endocrinology",
    sampleType: "Serum",
    turnaroundHours: 24,
    listPrice: 900,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Fasting preferred. Disclose B12 or multivitamin use.",
  },
  {
    id: "mst-tsh",
    code: "TSH",
    name: "Thyroid Stimulating Hormone",
    department: "Endocrinology",
    sampleType: "Serum",
    turnaroundHours: 8,
    listPrice: 400,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Morning sample preferred. Note thyroid medication timing.",
  },
  {
    id: "mst-lipid",
    code: "LIPID",
    name: "Lipid Profile",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 8,
    listPrice: 700,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Fast 9–12 hours. No alcohol for 24 hours. Avoid a heavy meal the night before.",
  },
  {
    id: "mst-lft",
    code: "LFT",
    name: "Liver Function Test",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 8,
    listPrice: 650,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Fasting preferred. Avoid alcohol for 24 hours.",
  },
  {
    id: "mst-kft",
    code: "KFT",
    name: "Kidney Function Test",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 8,
    listPrice: 650,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Stay well hydrated. List current medications.",
  },
  {
    id: "mst-thyroid",
    code: "THYROID",
    name: "Thyroid Profile (T3, T4, TSH)",
    department: "Endocrinology",
    sampleType: "Serum",
    turnaroundHours: 12,
    listPrice: 800,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Morning sample preferred. Note thyroid medication timing.",
  },
  {
    id: "mst-urine",
    code: "URINE",
    name: "Urine Routine & Microscopy",
    department: "Pathology",
    sampleType: "Urine",
    turnaroundHours: 4,
    listPrice: 180,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Mid-stream clean catch. Prefer first morning sample. Empty bladder only if instructed.",
  },
  {
    id: "mst-psa",
    code: "PSA",
    name: "Prostate Specific Antigen",
    department: "Endocrinology",
    sampleType: "Serum",
    turnaroundHours: 24,
    listPrice: 950,
    requiresPhysicianOrder: true,
    genderRestriction: "male",
    minAge: 40,
    maxAge: null,
    defaultPrepNotes: "Avoid ejaculation and cycling for 48 hours before the test.",
  },
  {
    id: "mst-pap",
    code: "PAP",
    name: "Pap Smear",
    department: "Pathology",
    sampleType: "Cervical smear",
    turnaroundHours: 48,
    listPrice: 1100,
    requiresPhysicianOrder: true,
    genderRestriction: "female",
    minAge: 21,
    maxAge: 65,
    defaultPrepNotes: "Avoid intercourse, douching, or vaginal medication for 48 hours. Do not schedule during menstruation.",
  },
  {
    id: "mst-iron",
    code: "IRON",
    name: "Iron Studies",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 12,
    listPrice: 850,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "Morning fasting sample preferred. Avoid iron supplements for 24 hours if advised.",
  },
  {
    id: "mst-crp",
    code: "CRP",
    name: "C-Reactive Protein",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 6,
    listPrice: 500,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No special preparation. Report recent illness or infection.",
  },
  {
    id: "mst-dengue",
    code: "DENGUE",
    name: "Dengue NS1 Antigen",
    department: "Microbiology",
    sampleType: "Serum",
    turnaroundHours: 8,
    listPrice: 1400,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No fasting. Best within 5 days of fever onset. Report allergies and current medications.",
  },
  {
    id: "mst-electrolytes",
    code: "LYTES",
    name: "Serum Electrolytes",
    department: "Biochemistry",
    sampleType: "Serum",
    turnaroundHours: 4,
    listPrice: 450,
    requiresPhysicianOrder: false,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No special preparation. List diuretics and supplements.",
  },
  {
    id: "mst-psmear",
    code: "PSMEAR",
    name: "Peripheral Blood Smear",
    department: "Hematology",
    sampleType: "EDTA whole blood",
    turnaroundHours: 12,
    listPrice: 400,
    requiresPhysicianOrder: true,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No special preparation. Usually ordered with CBC.",
  },
  {
    id: "mst-hba",
    code: "HBELEC",
    name: "Hemoglobin Electrophoresis",
    department: "Hematology",
    sampleType: "EDTA whole blood",
    turnaroundHours: 48,
    listPrice: 1600,
    requiresPhysicianOrder: true,
    genderRestriction: "any",
    minAge: null,
    maxAge: null,
    defaultPrepNotes: "No transfusion in the last 3 months if possible. Disclose family history of hemoglobinopathy.",
  },
];
